language: ruby
rvm:
- 2.2
- 2.1
- 2.0
- 1.9.3
services:
- docker
script:
- >
  wget -O- bit.ly/ansibletest | env DOCKER_IMAGES="ubuntu:14.04
  ubuntu:16.04"
  ANSIBLE_VERSIONS="1.4.4 1.6.1 1.8.4 2.0.0.2 2.1.0.0" sh -x
after_failure:
- cat role-tester-ansible-master/.kitchen.yml
- cat role-tester-ansible-master/.kitchen.local.yml
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    on_success: change
    on_failure: change
    rooms:
    - secure: HMnk7Rcizl/v0Qk5kA3YRgFtR80y1nBTOiu0ZTs7/AVJhnanR1RlEz/xndI/+sw1qWzdQ1lvmdHDQ1gEDTEbuWAaYEndrHxShP4dJ+UaZWS+X+sdld7m3O6/i1C6OZrsW+9boosfyg3jXIKaOpnBdAp3ucUq6hCuZDda42DHYamh5njcoZ/rn0yd6be+upMvlLzX8B7ibsy8i49pES2J92cQRI8MO++BiRIFxdEOBJM6pKEJOPhg8Zya3pr7juXV+yjQaK4SKp1noXOeukDgqq4yBEbQdxq84d4yjYn/4OOMcXoy2dMOZ8icOc//EDIHrn5v3FL0VkC2f8tg60AbtrwDSllop/l94r83bAyTBAcUkC3Ol47woT3TZp0FHHdUJJwkSHq5HTsK3A6+tC3wRUWs0Axh3wRmK44C1S404e/CcD1aEDBW+Lq5/rQLxw6HJJr2vWjawPL3zMWBNVHEC2vBiKCzJnVMQeG5e/6gfkYv3/qoF2mKHT4IA2VbEajGrfhapDyOq2ybVBS2PiVRrRZaOBn3FE44NQ476qu4+m7v4GZZbI9Ey1ti719N8G6f/XGSpetV4plMljpgWENQwI6CvvyUTs1Y97Q8sxf7poY3OTZXkucF/E0hKPYHMnfyFk1XkJP4vNU+JnGO0Q5N4q8kWe88LGPYcrZA/Rt8lqI=
  email:
    recipients:
      secure: ngxfz0P7I/5IWX2C4FjD24JvoV1fqLIEy8PyxwCCTB22ML1hwhqyjE1B8qIw2rIHdy0IOZR+DHjnNZlv6QdBZ77D7qys+1nGweARH0ermKhuL5J+I/ENg43RWU624MEiSX5+w6KUyEKOLdFBo6lUFbUeVj6rgEKg02eJsiSK+e1vC5XSgqT6p8KcDxpEclCS7cMVMZIwUqbj+0e/O0EGXYKCVNd5z+HNRiTsS1KLQnSTgdvfr6YhETzwwRsfIq0K+MXBKpr5QhhUPFcZlvyueDdyGFm2oaAT5FCV84sWdzTtksmKrE8qy9qVIELTLsWjTorO4ZjtwXwn8EkmsX7IGq3nhZhU+iS+2ieU4/zxFWhX2kzfbqMuZ4Qfqfgx1djbP1FvWXiBHKFAGRPkfihb4kpt4gujFJexgnq7T5LJ79gg+tQ1owCha7OoS+cYwfIVjajEwfCT9oN+LRWs/CmDUX6a8+DjLWP7N8Bbizfg4RYrqUBDbE4LjahP70pMRX4qF87C5F23+orZAmLLIEqpUOa647oV84UZun4cP5yBF46N9eDd1VagqObgJ5+VM1eM15oJzRoXRm1jxytdhpg3K7nmsxKhsx2ohH53dSBEdOiRqglcN3LkbxiQaM4UmvzAlAQEoY1gA+e3FEdhfSjk7ogxiX3ChXct5s4PccbFdpE=
